### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by edgardomortiz** [ndierckx/NOVOPlasty#18] opened 2017-08-11 16:05 UTC
Hello, I have been trying to assemble Ericaceae chloroplasts, I had to use multiple seeds and only using psaA as seed gave somewhat longer contigs, but with missing pieces. Anyway, while assembling one of these I got this error message and after that NOVOplasty just exits:

```
-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.2
Author: Nicolas Dierckxsens, (c) 2015-2017
-----------------------------------------------


gzip: stdout: Broken pipe

Reading Input......OK

Input parameters from the configuration file:   *** Verify if everything is correct ***

Project name         = Demlut_EMO2525_psaA
Insert size          = 300
Insert size auto     = yes
Read Length          = 101
Type                 = chloro
Genome range         = 120000-200000
K-mer                = 39
Insert range         = 1.6
Insert range strict  = 1.2
Paired/Single        = PE
Max memory           =
Extended log         = 0
Save assembled reads = yes
Combined reads       = ../../Demlut_EMO2525_PE_clPE.r100.fq.gz
Forward reads        =
Reverse reads        =
Seed Input           = ../Vaccinium_psaA.fasta
Reference sequence   =
Chloroplast sequence =


Building Hash Table......OK

Subsampled fraction: 100.00 %

Retrieve Seed......OK

Initial read retrieved successfully: CAGAAGTCCAAATTTTGGTAGATAGGGATCCAGTAAAAACTTCTTTCGAGGAATGGGCCAGACCGGGCCATTTCTCAAGAACAATAGCGAAAGGCCCGGAT
78092 bp assembledQuantifier follows nothing in regex; marked by <-- HERE in m/* <-- HERE GAAAAATGGCAG/ at /home1/02728/emo347/bin/NOVOPlasty/NOVOPlasty2.6.2.pl line 15973, <INPUT3> line 31.
```
Any help is appreciated

**Comment by ndierckx** [comment] 2017-08-11 17:45
Hi,
Thanks for reporting the bug, it should be fixed now, so you can download it again from github
As for the multiple seeds, it is necessary when there are gaps in coverage.
Can be caused by trimming or too low coverage or if you have capture DNA

**Comment by edgardomortiz** [comment] 2017-08-11 19:13
Thanks! I will try the new version right away.
My reads are not too trimmed and I don't have capture DNA. What I am thinking is I have stretches of repeats much longer than the insert size.

**Comment by ndierckx** [comment] 2017-08-12 17:03
That should not be a problem, it can jump repetitive regions.
You could send me the extended log and tell I can maybe see what the reason is

**Comment by edgardomortiz** [comment] 2017-08-12 19:40
I've got the extended log but is 200MB, how should I send it to you?

**Comment by edgardomortiz** [comment] 2017-08-12 19:43
Here it goes
[log_extended_Demlut_EMO2525_psaA.txt.gz](https://github.com/ndierckx/NOVOPlasty/files/1220017/log_extended_Demlut_EMO2525_psaA.txt.gz)

**Comment by edgardomortiz** [comment] 2017-08-23 18:25
Any ideas to improve my assembly?

**Comment by ndierckx** [comment] 2017-08-24 00:53
Hi,
Sorry forgot to look at it, looks indeed like multiple long repetitive regions are causing some problems
Could you send the Merged file too?
Will look at it tomorrow

**Comment by edgardomortiz** [comment] 2017-08-25 14:38
Hi again Nicolas, this is the entire content of the Merged file:

```
LINKS BETWEEN CONTIGS
---------------------

07----> REPETITIVE REGION----> 08
08----> 14 OR 09
19----> 14 OR 09
06----> 03 OR 02
09----> 12 OR 10
START----> 01
01----> 03 OR 02
04----> 07 OR 05
18----> REPETITIVE REGION----> 19
16----> 11 OR 13
05----> 06 OR 04
11----> 14 OR 09
17----> 03 OR 02
13----> 03 OR 02
10----> 11 OR 13
03----> 06 OR 04
14----> 15 OR 18
15----> 17 OR 16
12----> 03 OR 02
02----> 03 OR 02


Each option has a separate fasta file
```

**Comment by ndierckx** [comment] 2017-08-28 02:27
Hi,
Could you run it again with version 2.6.3.
And send me the extended log again (there should be some improvement)

**Comment by ndierckx** [comment] 2017-08-28 14:22
And since you have high coverage, maybe better to use a kmer of 39

**Comment by edgardomortiz** [comment] 2017-08-28 21:10
This is the new log, increasing the kmer reduced the total assembly size:

```
-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.3
Author: Nicolas Dierckxsens, (c) 2015-2017
-----------------------------------------------


Input parameters from the configuration file:   *** Verify if everything is correct ***

Project name         = Demlut_EMO2525_psaA
Insert size          = 350
Insert size auto     = yes
Read Length          = 101
Type                 = chloro
Genome range         = 120000-200000
K-mer                = 39
Insert range         = 1.6
Insert range strict  = 1.2
Paired/Single        = PE
Max memory           =
Extended log         = 1
Save assembled reads = yes
Combined reads       = ../../Demlut_EMO2525_PE_clPE.r100.fq.gz
Forward reads        =
Reverse reads        =
Seed Input           = ../Vaccinium_psaA.fasta
Reference sequence   =
Chloroplast sequence =

Subsampled fraction: 100.00 %

Initial read retrieved successfully: CAGAAGTCCAAATTTTGGTAGATAGGGATCCAGTAAAAACTTCTTTCGAGGAATGGGCCAGACCGGGCCATTTCTCAAGAACAATAGCGAAAGGCCCGGAT

Start Assembly...


------------Assembly 1 finished: Contigs are automatically merged in Merged_contigs file------------

Contig 01                  : 62281 bp
Contig 02                  : 329 bp
Contig 03                  : 1776 bp
Contig 04                  : 3013 bp
Contig 05                  : 3022 bp

Total contigs              : 5
Largest contig             : 62281 bp
Smallest contig            : 329 bp
Average insert size        : 320 bp


-----------------------------------------Input data metrics-----------------------------------------

Total reads                : 30538664
Aligned reads              : 652208
Assembled reads            : 134112
----------------------------------------------------------------------------------------------------
```
And here the extended log:

[log_extended_Demlut_EMO2525_psaA.txt.gz](https://github.com/ndierckx/NOVOPlasty/files/1258379/log_extended_Demlut_EMO2525_psaA.txt.gz)

**Comment by ndierckx** [comment] 2017-08-28 23:03
Hi,

Looks like besides the repetitive regions, a region of the chloroplast is massively duplicated in the nuclear genome and/or chloroplast genome itself, which is causing some problems. This is the first time I encountered this ,so I made some chances on the github, maybe you can download it again and send me the extended log again.
Or if I can access the data, I can try myself...

Maybe you could also try with a different seed, although it looks there quite a lot of complex regions.
And have you tried to give a reference? This option doesn't work optimal yet but I am improving it.

**Comment by edgardomortiz** [comment] 2017-08-30 15:53
Link to data sent to your email (the one on the NOVOplasty paper), I hope it helps.

**Comment by ndierckx** [comment] 2017-08-31 23:06
Hi, 

I got the data, will try it out tomorrow.

**Comment by edgardomortiz** [comment] 2017-09-05 21:31
Great, I will remove the file from Drive then.

**Comment by ndierckx** [comment] 2017-09-07 01:21
Hi,

Couldn't make it work yet. Do you have a close reference of this genome?

**Comment by edgardomortiz** [comment] 2017-09-07 02:21
There are two versions of the cranberry plastid genome, that is the closest I know of, GenBank IDs   NC_019616.1 and JQ248601.1

**Comment by edgardomortiz** [comment] 2017-09-11 23:07
Any luck with those references? I am suspecting these genomes might not be really circular...

**Closed** 2019-07-30 11:01 UTC
